[build]
    functions = "functions"
[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://velvety-lolly-696161.netlify.app"
  status = 200